# -*- coding: utf-8 -*-
"""CCBANK

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1docGtNvmAo-zK33jI7aFUogw3ZW5V9El
"""

def linha():
  print('=' * 25)

def linhamaior():
  print('=' * 50)

def linhagigante():
  print('=' * 100)


admin = ['Renan' , 123987]  # Informações do ADMINISTRADOR (ROOT)


class Cliente:              # Informações do cliente
  nome = ''
  sobrenome = ''
  cpf = 0
  cartao = 0
  senha = 0
  credito = 0
  compras = ''

class ComprasDoCliente:     # Informações do cartão do cliente
  compras = 0
  valor = 0
  data = ''
  categoria = ''
  loja = ''
  
                            # Para validar o cpf
def validarCPF(numbers):                                    
    cpf = [int(char) for char in numbers if char.isdigit()]
    if len(cpf) != 11:
        return False
    if cpf == cpf[::-1]:
        return False
    for i in range(9, 11):
        value = sum((cpf[num] * ((i+1) - num) for num in range(0, i)))
        digit = ((value * 10) % 11) % 10
        if digit != cpf[i]:
            return False
    return True


clientesLista = []
comprasLista = []

linha()
print(' Boas-vindas ao BANCO CC')
linha()

print()

linhamaior()
print(' Digite o número da ação que deseja realizar')
linhamaior()

print()

while True:
  id == 0
  print('1 - Abrir uma nova conta' )
  print('2 - Realizar compra' )
  print('3 - Extrato da conta ')
  print('4 - Realizar depósito ')
  print('5 - Encerrar')

  id = int(input('\n'))

# =========================== Se forem digitados números inválidos

  while id>5:
    print('1 - Abrir uma nova conta' )
    print('2 - Realizar compra' )
    print('3 - Extrato da conta ')
    print('4 - Realizar depósito')
    print('5 - Encerrar')
    linhamaior()
    id = int(input('Por favor, digite um número válido!\n'))
    linhamaior()

  while id<1:
    print('1 - Abrir uma nova conta' )
    print('2 - Realizar compra' )
    print('3 - Extrato da conta ')
    print('4 - Realizar depósito')
    print('5 - Encerrar')
    linhamaior()
    id = int(input('Por favor, digite um número válido!\n'))
    linhamaior()



# ========================== ABRIR NOVA CONTA

  if id == 1:
    linhagigante()
    print('           Para abrir uma nova conta são necessárias as informações do ADMINISTRADOR')
    linhagigante()

    print()

    while True:
      admlogin = str(input('Usuário: '))
      admsenha = int(input('Senha: '))

      if admlogin != admin[0] or admsenha != admin[1]:
        print()
        linhagigante()
        print('         As informações não estão corretas, por favor digite as informações do ADMINISTRADOR ')
        linhagigante()
      else:
        break

    print()

    linhamaior()
    print('Informações corretas! Login efetuado com sucesso!')
    linhamaior()
    print('Agora vamos precisar de suas informações: ')
    linhamaior()

    dados = Cliente()
    dados.primeiro_nome = str(input(' - Nome:\n '))
    dados.ultimo_nome = str(input(' - Sobrenome:\n '))
  
  
    while True:           #Cadastrar CPF
      dados.CPF = str(input(' - Seu CPF:\n '))
      if validarCPF(dados.CPF):
        linhamaior()
        print(' - CPF cadastrado com sucesso! ')
        linhamaior()
        break
      else:
        print(' - Seu CPF é inválido, digite um CPF válido!')  


                        #Criação da Senha
    while True:           
      senhacliente = input(' - Crie uma senha de seis números:\n ')
      novasenha = str(senhacliente)
      if len(novasenha) > 6 or len(novasenha) < 6:
        print(' - Essa senha não é permitida, digite uma senha de seis números\n ')
      else:
        break
                    
                        #Confirmação da Senha
    while True:          
      confirmasenha = input(' - Repita a senha digitada:\n ')
      if confirmasenha != senhacliente:
        print('As senhas digitadas são diferentes! Digite novamente:')
      else:
        break
    dados.senha = senhacliente
  
    print()
    linhamaior()

    print('Qual o valor que deseja depositar em sua conta? ')
    dados.credito = int(input('\n'))
    linhamaior()

    while True:           #Gerar número do cartão
      import random
      numerocar = random.randint(1000000000000, 10000000000000)
      if numerocar not in clientesLista:
        dados.cartão = numerocar
        break

    print(f' - Agora você tem R$ {dados.credito},00 de saldo em seu cartão')
    linhamaior()
    print()
    print()
    linhamaior()
    print('          Conta registrada com sucesso! \n         Obrigado por escolher a BANCO CC! ')
    linhamaior()

    print()
    linhamaior()
    print(f'- O número do seu cartão é: {dados.cartão} ')
    linhamaior()
    
    print()
    clientesLista.append(dados)
    print()

# ============================== REALIZAR COMPRA

  elif id == 2:
    linhagigante()
    print('                     Para realizar uma compra serão necessárias as informações: ')
    linhagigante()
    login = int(input(' - Número do cartão:\n'))
    loginsenha = input(' - Senha:\n ')

    while True:
      for x in clientesLista:
        if loginsenha == x.senha and login == x.cartão:
          compra = ComprasDoCliente()
          compra.compras = login
          compra.valor = float(input(' - Qual o valor da compra?\n '))
          if compra.valor <= x.credito:
            x.credito = x.credito - compra.valor
            compra.data = input(' - Qual da data da compra? (Exemplo: 21 de dezembro de 2020\n ')
            compra.categoria = input(' - Qual a categoria? (Exemplo: Viagem / Farmácia / Lazer\n ')
            compra.loja = input(' - Qual o nome da loja? ')

            print('Compra finalizada!')
            print(f'Seu saldo agora é de {x.credito} reais')
            linhamaior()

            comprasLista.append(compra)
          
            break
          else:
            print('Não é possível realizar a operação! Saldo insuficiente! ')
            linhamaior()

      break
  # ===================================== EXTRATO

  elif id == 3:
    linhamaior()
    print('Para realizar o extrato digite as seguintes informações de sua conta:')
    linhamaior()

    logincompra = int(input(' - Número do cartão:\n '))

    for x in comprasLista:
      if logincompra == x.compras:
        linhamaior()
        print(f'Valor da compra ->    {x.valor}')
        print(f'Data da compra  ->    {x.data}')
        print(f'Categoria       ->    {x.categoria}')
        print(f'Nome da loja    ->    {x.loja}')
        linhamaior()
      elif logincompra != numerocar:
        print('Informações não reconhecidas, digite os dados corretos!')
        logincompra = int(input(' - Número do cartão:\n '))
    for x in clientesLista:
      print(f'Seu saldo é de {x.credito} reais')
      linhamaior()


  # ===================================== DEPOSITAR

  elif id == 4:
    linhamaior()
    print('Para realizar o pagamento informe os dados: ')
    print('Para sair, digite 0')
    linhamaior()

    loginpagamento = int(input(' - Número do cartão: '))
    for x in clientesLista: 
        if loginpagamento == x.cartão:
          print(f'Qual o valor do depósito? ')
          deposito = int(input())

          print(f'O valor depositado foi de R${deposito},00')
          print(f'Seu saldo agora é de R${deposito + x.credito}')
        
          print()
        if loginpagamento == 0:
          linhamaior()
          break

        elif loginpagamento != numerocar:
          print('Informações não reconhecidas, digite os dados corretos!')
          loginpagamento = int(input(' - Número do cartão:\n '))  

  # ===================================== FINALIZAR

  if id == 5:
    print()
    linhamaior()
    print('                 Sessão Finalizada')
    linhamaior()
    break